### ISSUE TITLE
Tags in items that have status 'draft'

### ISSUE THREAD

**Issue by evertalbers** [axsy/bolt-extension-tagcloud#6]
When you use tags in a blog post that you save as 'draft', the tags are shown in the tagcloud. I's probably better not to show tags from unpublished items.

_(Otherwise the extension works fine, thanks!)_

**Comment by axsy** [comment]
Hey, thank you for the notice. Unfortunately I don't have a time to support this extension further, if it makes you uncomfortable while using the extension, would you create a pull request with the fix?

**Comment by evertalbers** [comment]
I am not very skilled in Php, but can I fix this in Twig? 
Then I might give it a try.

**Comment by axsy** [comment]
No, it requires some minor changes to SQL query that grabs the tags. Anyway, I pushed the fix, check it out.

**Comment by evertalbers** [comment]
Solved, thanks a lot!
